# Generated by Django 3.1.2 on 2020-10-31 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import turkle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('allotted_assignment_time', models.IntegerField(default=24)),
                ('assignments_per_task', models.IntegerField(default=1, verbose_name='Assignments per Task')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_permissions', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=1024)),
                ('login_required', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=1024)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'permissions': (('can_work_on_batch', 'Can work on Tasks for this Batch'),),
            },
            bases=(turkle.models.TaskAssignmentStatistics, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('input_csv_fields', models.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkle.batch')),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkle.task')),
            ],
            options={
                'verbose_name': 'Task Assignment',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('assignments_per_task', models.IntegerField(db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_permissions', models.BooleanField(default=False)),
                ('filename', models.CharField(blank=True, max_length=1024)),
                ('html_template', models.TextField()),
                ('html_template_has_submit_button', models.BooleanField(default=False)),
                ('login_required', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=1024)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fieldnames', models.JSONField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'permissions': (('can_work_on', 'Can work on Tasks for this Project'),),
            },
            bases=(turkle.models.TaskAssignmentStatistics, models.Model),
        ),
        migrations.AddField(
            model_name='batch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkle.project'),
        ),
    ]
