# Generated by Django 2.2.19 on 2021-03-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkle', '0009_batch_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'permissions': (('can_work_on', 'Can work on Tasks for this Project'),), 'verbose_name': 'Project'},
        ),
    ]
